apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: admin-ayusha.com
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-server-srv
                port:
                  number: 3000

          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: admin-client-srv
                port:
                  number: 3000
    - host: seller-ayusha.com
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: seller-server-srv
                port:
                  number: 3000

          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: seller-client-srv
                port:
                  number: 3000
    - host: ayusha-ayur.com
      http:
        paths:
          - path: /api/store-front/?(.*)
            pathType: Prefix
            backend:
              service:
                name: storefront-server-srv
                port:
                  number: 3000
          - path: /api/checkout/?(.*)
            pathType: Prefix
            backend:
              service:
                name: checkout-server-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: storefront-client-srv
                port:
                  number: 3000
